sum_level_info <- tibble::tribble(
  ~sum_level, ~name, ~geo,
  "010", "United States", "US",
  "010", "United States; Urban", "US",
  "010", "United States; Rural", "US",
  "010", "United States; American Indian Reservation and Trust Land-Federal", "US",
  "010", "United States; American Indian Reservation and Trust Land-State", "US",
  "010", "United States; Oklahoma Tribal Statistical Area", "US",
  "010", "United States; Tribal Designated Statistical Area", "US",
  "010", "United States; Alaska Native Village Statistical Area", "US",
  "010", "United States; State Designated Tribal Statistical Area (Formerly SDAISA)", "US",
  "010", "United States; Hawaiian Home Land", "US",
  "010", "United States; In Metropolitan or Micropolitan Statistical Area", "US",
  "010", "United States; In Metropolitan Statistical Area", "US",
  "010", "United States; In Metropolitan Statistical Area-In Principal City", "US",
  "010", "United States; In Metropolitan Statistical Area-Not In Principal City", "US",
  "010", "United States; In Micropolitan Statistical Area", "US",
  "010", "United States; In Micropolitan Statistical Area-In Principal City", "US",
  "010", "United States; In Micropolitan Statistical Area-Not In Principal City", "US",
  "010", "United States; Not In Metropolitan or Micropolitan Statistical Area", "US",
  "010", "United States; Not In Metropolitan Statistical Area", "US",
  "020", "Region", "US",
  "020", "Region; Urban", "US",
  "020", "Region; Rural", "US",
  "020", "Region; In Metropolitan or Micropolitan Statistical Area", "US",
  "020", "Region; In Metropolitan Statistical Area", "US",
  "020", "Region; In Metropolitan Statistical Area-In Principal City", "US",
  "020", "Region; In Metropolitan Statistical Area-Not In Principal City", "US",
  "020", "Region; In Micropolitan Statistical Area", "US",
  "020", "Region; In Micropolitan Statistical Area-In Principal City", "US",
  "020", "Region; In Micropolitan Statistical Area-Not In Principal City", "US",
  "020", "Region; Not In Metropolitan or Micropolitan Statistical Area", "US",
  "020", "Region; Not In Metropolitan Statistical Area", "US",
  "030", "Division", "US",
  "030", "Division; Urban", "US",
  "030", "Division; Rural", "US",
  "030", "Division; In Metropolitan or Micropolitan Statistical Area", "US",
  "030", "Division; In Metropolitan Statistical Area", "US",
  "030", "Division; In Metropolitan Statistical Area-In Principal City", "US",
  "030", "Division; In Metropolitan Statistical Area-Not In Principal City", "US",
  "030", "Division; In Micropolitan Statistical Area", "US",
  "030", "Division; In Micropolitan Statistical Area-In Principal City", "US",
  "030", "Division; In Micropolitan Statistical Area-Not In Principal City", "US",
  "030", "Division; Not In Metropolitan or Micropolitan Statistical Area", "US",
  "030", "Division; Not In Metropolitan Statistical Area", "US",
  "040", "State", "State",
  "040", "State; Urban", "State",
  "040", "State; Rural", "State",
  "040", "State; In Metropolitan or Micropolitan Statistical Area", "State",
  "040", "State; In Metropolitan Statistical Area", "State",
  "040", "State; In Metropolitan Statistical Area-In Principal City", "State",
  "040", "State; In Metropolitan Statistical Area-Not In Principal City", "State",
  "040", "State; In Micropolitan Statistical Area", "State",
  "040", "State; In Micropolitan Statistical Area-In Principal City", "State",
  "040", "State; In Micropolitan Statistical Area-Not In Principal City", "State",
  "040", "State; Not In Metropolitan or Micropolitan Statistical Area", "State",
  "040", "State; Not In Metropolitan Statistical Area", "State",
  "050", "State-County", "State",
  "060", "State-County-County Subdivision", "State",
  "067", "State-County-County Subdivision-Subminor Civil Division", "State",
  "070", "State-County-County Subdivision-Place/Remainder", "State",
  "080", "State-County-County Subdivision-Place/Remainder-Census Tract", "State",
  "140", "State-County-Census Tract", "State",
  "150", "State-County-Census Tract-Block Group", "State",
  "155", "State-Place-County", "State",
  "160", "State-Place", "State",
  "170", "State-Consolidated City", "State",
  "172", "State-Consolidated City-Place Within Consolidated City", "State",
  "230", "State-Alaska Native Regional Corporation", "State",
  "250", "American Indian Area/Alaska Native Area/Hawaiian Home Land", "US",
  "251", "American Indian Area-Tribal Subdivision/Remainder", "US",
  "252", "American Indian Area/Alaska Native Area (Reservation or Statistical Entity Only)", "US",
  "254", "American Indian Area (Off-Reservation Trust Land Only)/Hawaiian Home Land", "US",
  "256", "American Indian Area-Tribal Census Tract", "US",
  "258", "American Indian Area-Tribal Census Tract-Tribal Block Group", "US",
  "260", "American Indian Area/Alaska Native Area/Hawaiian Home Land-State", "State",
  "269", "American Indian Area/Alaska Native Area/Hawaiian Home Land-StatePlace/Remainder", "State",
  "270", "American Indian Area/Alaska Native Area/Hawaiian Home Land-State-County", "State",
  "280", "State-American Indian Area/Alaska Native Area/Hawaiian Home Land", "State",
  "283", "State-American Indian Area/Alaska Native Area (Reservation or Statistical Entity Only)", "State",
  "286", "State-American Indian Area (Off-Reservation Trust Land Only)/Hawaiian Home  Land", "State",
  "290", "American Indian Area-Tribal Subdivision/Remainder-State", "State",
  "291", "American Indian Area (Reservation Only)-Tribal Census Tract", "US",
  "292", "American Indian Area (Off-Reservation Trust Land Only)-Tribal Census Tract", "US",
  "293", "American Indian Area (Reservation Only)-Tribal Census Tract-Tribal Block Group", "US",
  "294", "American Indian Area (Off-Reservation Trust Land Only)-Tribal Census Tract-Tribal Block Group", "US",
  "310", "Metropolitan Statistical Area/Micropolitan Statistical Area", "US",
  "311", "Metropolitan Statistical Area/Micropolitan Statistical Area-State", "State",
  "312", "Metropolitan Statistical Area/Micropolitan Statistical Area-State-Principal City", "State",
  "313", "Metropolitan Statistical Area/Micropolitan Statistical Area-State-County", "State",
  "314", "Metropolitan Statistical Area-Metropolitan Division", "US",
  "315", "Metropolitan Statistical Area-Metropolitan Division-State", "State",
  "316", "Metropolitan Statistical Area-Metropolitan Division-State-County", "State",
  "320", "State-Metropolitan Statistical Area/Micropolitan Statistical Area", "US",
  "321", "State-Metropolitan Statistical Area/Micropolitan Statistical Area-Principal City", "State",
  "322", "State-Metropolitan Statistical Area/Micropolitan Statistical Area-County", "State",
  "323", "State-Metropolitan Statistical Area-Metropolitan Division", "State",
  "324", "State-Metropolitan Statistical Area-Metropolitan Division-County", "State",
  "330", "Combined Statistical Area", "US",
  "331", "Combined Statistical Area-State", "State",
  "332", "Combined Statistical Area-Metropolitan Statistical Area/Micropolitan Statistical Area", "US",
  "333", "Combined Statistical Area-Metropolitan Statistical Area/Micropolitan Statistical Area-State", "State",
  "335", "Combined New England City and Town Area", "US",
  "336", "Combined New England City and Town Area-State", "State",
  "337", "Combined New England City and Town Area-New England City and Town Area", "US",
  "338", "Combined New England City and Town Area-New England City and Town Area-State", "State",
  "340", "State-Combined Statistical Area", "State",
  "341", "State-Combined Statistical Area-Metropolitan Statistical Area/Micropolitan Statistical Area", "State",
  "345", "State-Combined New England City and Town Area", "State",
  "346", "State-Combined New England City and Town Area-New England City and Town Area", "State",
  "350", "New England City and Town Area", "US",
  "351", "New England City and Town Area-State", "State",
  "352", "New England City and Town Area-State-Principal City", "State",
  "353", "New England City and Town Area-State-County", "State",
  "354", "New England City and Town Area-State-County-County Subdivision", "State",
  "355", "New England City and Town Area (NECTA)-NECTA Division", "US",
  "356", "New England City and Town Area (NECTA)-NECTA Division-State", "State",
  "357", "New England City and Town Area (NECTA)-NECTA Division-State-County", "State",
  "358", "New England City and Town Area (NECTA)-NECTA Division-State-CountyCounty Subdivision", "State",
  "360", "State-New England City and Town Area", "State",
  "361", "State-New England City and Town Area-Principal City", "State",
  "362", "State-New England City and Town Area-County", "State",
  "363", "State-New England City and Town Area-County-County Subdivision", "State",
  "364", "State-New England City and Town Area (NECTA)-NECTA Division", "State",
  "365", "State-New England City and Town Area (NECTA)-NECTA Division-County", "State",
  "366", "State-New England City and Town Area (NECTA)-NECTA Division-CountyCounty Subdivision", "State",
  "400", "Urban Area", "US",
  "500", "State-Congressional District", "State",
  "510", "State-Congressional District-County", "State",
  "550", "State-Congressional District-American Indian Area/Alaska Native Area/Hawaiian Home Land", "State",
  "610", "State-State Legislative District (Upper Chamber)", "State",
  "612", "State-State Legislative District (Upper Chamber)-County", "State",
  "620", "State-State Legislative District (Lower Chamber)", "State",
  "622", "State-State Legislative District (Lower Chamber)-County", "State",
  "795", "State-Public Use Microdata Sample Area (PUMA)", "State",
  "860", "5-digit ZIP Code Tabulation Area", "US",
  "950", "State-School District (Elementary)/Remainder", "State",
  "960", "State-School District (Secondary)/Remainder", "State",
  "970", "State-School District (Unified)/Remainder", "State"
)

devtools::use_data(sum_level_info, overwrite = TRUE)
